apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests-gke/config-map.yml
- manifests-gke/gateway.yml
- manifests-gke/deployment.yml
- manifests-gke/log-output-svc.yml
- manifests-gke/ping-pong-svc.yml
- manifests-gke/log-output-route.yml
- manifests-gke/ping-pong-route.yml
images:
- name: LOGREAD_APP_IMAGE
  newName: alterho/log-output
  newTag: main-read-76da07d790589183b4fe86522495c6c3200bd0fc
- name: LOGWRITE_APP_IMAGE
  newName: alterho/log-output
  newTag: main-write-76da07d790589183b4fe86522495c6c3200bd0fc
namespace: exercises
