apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/serviceaccount.yml
  - manifests/clusterrole.yml
  - manifests/clusterrolebinding.yml
  - manifests/resourcedefinition.yml
  - manifests/ds-controller-dep.yml
