apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-tmp-files
          emptyDir: {}
      containers:
        - name: log-output-write
          image: alterho/log-output:2.1-write
          volumeMounts:
            - name: shared-tmp-files
              mountPath: /usr/src/app/tmp
        - name: log-output-read
          image: alterho/log-output:2.1-read
          volumeMounts:
            - name: shared-tmp-files
              mountPath: /usr/src/app/tmp
