apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-files
          emptyDir: {}
      containers:
        - name: log-output-write
          image: alterho/log-output:1.10-write
          volumeMounts:
            - name: shared-files
              mountPath: /usr/src/app/files
        - name: log-output-read
          image: alterho/log-output:1.10-read
          volumeMounts:
            - name: shared-files
              mountPath: /usr/src/app/files
