apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests-gke/postgres-secret.yml
  - manifests-gke/analysistemplate.yml
  - manifests-gke/deployment.yml
images:
  - name: PINGPONG_APP_IMAGE
    newName: alterho/ping-pong:4.1.2
