services:
  express-prod:
    build:
      context: .
      dockerfile: Dockerfile
    image: todo-backend:prod
    container_name: todo-backend-prod
    depends_on:
      - database-migrations
      - nats
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=database
      - POSTGRES_PASSWORD=postgres

  express-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: todo-backend:dev
    container_name: todo-backend-dev
    depends_on:
      - database-migrations
      - nats
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=database
      - POSTGRES_PASSWORD=postgres
    volumes:
      # use local bind mounts as Docker watch sync + tsx watch was unreliable
      # with this setup only changes in /src file are reflected live to the container
      # everything else is baked into the container at build time
      - ./src:/app/src # /app is the WORKDIR in container
    develop:
      watch:
        - action: rebuild
          path: package.json

  database:
    image: postgres:18.4
    container_name: postgres-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres

  database-migrations:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-backend-migrations
    depends_on:
      - database
    environment:
      - DATABASE_HOST=database
      - POSTGRES_PASSWORD=postgres
    command: ['npx', 'drizzle-kit', 'migrate']

  nats:
    image: nats:2.14-alpine
    container_name: nats-service
    ports:
      - '4222:4222' # client traffic
      - '8222:8222' # HTTP reporting

networks:
  default: # rename default network
    name: local-network
