ARG NODE_VERSION=alpine

# Development stage: install all dependencies and serve with hot-reload
FROM node:${NODE_VERSION} AS dev

WORKDIR /app

RUN --mount=type=bind,source=package.json,target=package.json \
    --mount=type=bind,source=package-lock.json,target=package-lock.json \
    --mount=type=cache,target=/root/.npm \
    npm ci --no-audit --no-fund

# .dockerignore must include node_modules/ so dependencies will not be overridden
COPY --chown=node:node . .

# USER node

# Expose the port that the application listens on.
EXPOSE 3000

# Run the application in development mode.
CMD ["npm", "run", "dev"]