apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: app-cache
          persistentVolumeClaim:
            claimName: local-volume1-claim
      containers:
        - name: todo-app
          image: alterho/todo-app:2.6
          volumeMounts:
            - name: app-cache
              mountPath: /app/cache
              subPath: todo-app # use a subfolder inside the PV
          env:
            - name: BACKEND_URL
              value: 'http://todo-backend-svc:1234'
            - name: PICTURE_URL
              value: 'https://picsum.photos/1200'
            - name: PICTURE_TTL_MINS
              value: '5'
            - name: MAX_TODO_LENGTH
              value: '120'
