apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: ping-pong-dep
  namespace: exercises
spec:
  replicas: 4
  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause:
            duration: 30s
        - setWeight: 50
        - analysis:
            templates:
              - templateName: cpu-rate
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: PINGPONG_APP_IMAGE
          env:
            - name: PORT
              value: '3001'
            - name: DATABASE_HOST
              # format is stateful-set.parent-service.namespace.svc.cluster.local
              value: 'postgres-ss-0.postgres-svc.exercises.svc.cluster.local'
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          readinessProbe:
            httpGet:
              path: '/readyz'
              port: 3001
