apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests-gke/namespace.yml
- manifests-gke/gke-dynamic-pvc.yml
- manifests-gke/deployment.yml
- manifests-gke/service.yml
- manifests-gke/ingress.yml
- manifests-gke/random-article-job.yml
images:
- name: TODO_APP_IMAGE
  newName: europe-north1-docker.pkg.dev/dwk-gke-501808/docker-images/todo-app
  newTag: project-argocd-5e2cc77017bb08df57381d8591b53777ed095dea
namespace: project-argocd
