apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests-gke/namespace.yml
- manifests-gke/gke-dynamic-pvc.yml
- manifests-gke/deployment.yml
- manifests-gke/service.yml
- manifests-gke/ingress.yml
- manifests-gke/random-article-job.yml
images:
- name: TODO_APP_IMAGE
  newName: europe-north1-docker.pkg.dev/dwk-gke-501808/docker-images/todo-app
  newTag: project-argocd-ddb4b712c0d10d081d3453dfc688b683767b06a7
namespace: project-argocd
