apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yml
  - ./../base
  - todo-backend/postgres-backup-cronjob.yml
patches:
  - path: broadcaster/deployment.yml
namespace: production
namePrefix: prod-
