apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-dep
  namespace: project
spec:
  replicas: 1
  strategy: # remove old pods before creating new ones
    type: Recreate
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: TODO_BACKEND_IMAGE
          env:
            - name: PORT
              value: '3000'
            - name: MAX_TODO_LENGTH
              value: '140'
          envFrom:
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: postgres-secret
