apiVersion: v1
kind: PersistentVolume
metadata:
  name: k3d-local-volume1
spec:
  storageClassName: local-volume1-storage
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  local:
    path: /tmp/volume1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3d-k3s-default-agent-0
