apiVersion: ENC[AES256_GCM,data:ph4=,iv:pp04d8/cJl4uy/mc5zXIyDbaKoDg/2SKMx+yC37MlCQ=,tag:9IKI+Xyim+64Ds6m87FyXQ==,type:str]
kind: ENC[AES256_GCM,data:bN4wAePZ,iv:t6xXpcd9D98kxeMlQ9xO8vZEQgZuupsGAMfDci0UahE=,tag:ouPXnmsk5UPOBaYR56C+3A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:gIgG/GHSd/B/ydtwevIdvmOY,iv:TgOhZiKGOed49opcaWerctl7EZ1Brc+4Gk5kIHqWqhg=,tag:ucao9M7eFulF2v6WwxTNJg==,type:str]
    namespace: ENC[AES256_GCM,data:wwiJ0IVqOQ==,iv:sa7gGR10W8wbEPMNw2x+ta0SwXnLpEaVjzT2drXnghI=,tag:k+xIUJFOGTi1Hftkk6P9Uw==,type:str]
data:
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:oVvwAI30ZDygn0zHdyHyNz9pw0of8KC/tb1GTFcC/YTJwqNjDQ68dd1VTd0aM6idiljfpckIEtkVC780rmZUJA==,iv:2KISkSKjgaJxP1ydoU3UIWokIXGzxkJcjT83a5dUGEU=,tag:+RqNmXIlPcuvSGUkY9lCxQ==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:hQCyeUdxl9nFhQOVHwcwYQ==,iv:qPdB6GDCCdicuB3cc3APJxMZ86G+qESkcJ+RHIaHrQM=,tag:zHJPh1wEfECXb384by5B/Q==,type:str]
sops:
    gcp_kms:
        - created_at: "2026-07-24T13:46:13Z"
          enc: CiQALnGy7Ak8wnCEo0uL3HjsNnx0TVenPeE9DWEUp3DqpZHcLNMSSACv+VWBSvf+qAd1voJEkW5VY0EAU1R/VmFdkCb3Xmey2YSTFi6ysMsQF4U5hnF/bCY7cP6n2SK0BuHboC+vemzdTQv/EsVBag==
          resource_id: projects/dwk-gke-501808/locations/global/keyRings/broadcaster-secrets/cryptoKeys/sops-key
    lastmodified: "2026-07-24T13:46:14Z"
    mac: ENC[AES256_GCM,data:J7g0YqEVSRqxFc6stPi4l+xhA/B0yCSQ0Z0T3Rr0mVTQDK9a0FTRdoo0fNe+Q9rAVoy6O07JXUM3PCDDA4aa1OAuNIU4VmMvN5jz3hHrGSBocJ6O3bg3jsP8N/5g7Q+lkcPDFqbd4ihVVQmqoVbXiEbMydtmXqaP8O47CHyYwAY=,iv:vH09M3ROFS5j05D6rND++wCnJJ0R+cv12xhqGXWclIE=,tag:A3et/vS9Yat0mfmrSGImsA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
