apiVersion: ENC[AES256_GCM,data:EWc=,iv:BlrtpYrTj82jvEkEEqdm3u7pmkPLVpE5DsKr7UeLuU4=,tag:Yn9ku0sFs1NZ87TjXKzANg==,type:str]
kind: ENC[AES256_GCM,data:hsAYuUZD,iv:ccvFVrIO6Vo0GQzaouK8AawklEjXRiOTZ8DxR1vXqc4=,tag:7RB2o4hvHiH6qJtdJTVGrA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:+0bWhT7QWKWCVaCNYAwJWEno,iv:CUVJ2aKG4p9Vj3ECn9viuWk0e2l0n7HPCHYt62mMuXI=,tag:kwdCMY9YL/6lwQcs6dXIxg==,type:str]
data:
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:bA14If8V0RGS8g3kOtuNwTN1lbEvlCLMqhqzeNy4ZTSq+z6UpHL4v5eEs8U57MbdEkP2op4BuT+gXqe6/K3lfA==,iv:Yvd13BbPchdQzVa4P8u3VrZKePjhr3FraiAdrk77Rug=,tag:mDxZEspMqWR5vK08wgJ4TA==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:Eh/Qzj/+ZrGeDMB5aL0i9A==,iv:DShKp+qYmHHgjRDzpRX/rdIJ4gF9V/7zISC3Om9FcB8=,tag:tTC3I1h2nYFT+d0/Gj5DQQ==,type:str]
sops:
    gcp_kms:
        - created_at: "2026-07-27T13:23:44Z"
          enc: CiQALnGy7BjNXuId7GGmKrY60OpsrS3MfC1Eh03rDU+P/FC2ZrQSSQCv+VWBf9hXyzpp1uMa+aBdsluhLihRHK0ozK8lEIBLviEsDSYo9cGSdQAMiOpScSN2Q7pTlJmcq+w9lIFp0gc/BaoINSM3V3E=
          resource_id: projects/dwk-gke-501808/locations/global/keyRings/broadcaster-secrets/cryptoKeys/sops-key
    lastmodified: "2026-07-27T13:23:45Z"
    mac: ENC[AES256_GCM,data:mz/ICD5uiTSIZr8pTK15ybkxG26TrAMWirtlBFCjyXmtGo62LPf2IRFg6PGA6LbiaFy0zpEcjKKIIU6rMSe1KZlGSs/4hcZBrnR0/h7oV5Z+P61KuJkU8PAjlN4FBAknF+gNNSx5gCXVNgUXwvmHGWjGOfJ0X4YAwr2rq5yCNVM=,iv:dPegSw9mdEgydCJwzq45vQn6PuD3oNkufZ/lFJ5ifvQ=,tag:pMmMC4vqx5iM7+BTmLruHQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
