const fs = require('node:fs').promises;
const path = require('node:path');
const crypto = require('node:crypto');

const express = require('express');
const app = express();

const logFilePath = path.join('/', 'usr', 'src', 'app', 'tmp', 'app.log');
const reqPath = path.join('/', 'usr', 'src', 'app', 'files', 'requests.log');

app.get('/', async (req, res) => {
  try {
    // read file generated by ping-pong app and generate dynamic content
    const pingpong = await fs.readFile(reqPath, 'utf8');
    const timestamp = new Date().toISOString();
    const uuid = crypto.randomUUID();
    const content = `${timestamp}: ${uuid}\nPing / Pongs: ${pingpong}`;

    res.set('Content-Type', 'text/plain');
    return res.status(200).send(content);
  } catch (err) {
    // with read errors print only the error message
    console.log(err.message);
    return res.status(500).send(err.message);
  }
});

// move previous functionality under a different route
app.get('/log', async (req, res) => {
  try {
    // send file content as response
    const content = await fs.readFile(logFilePath, 'utf8');
    res.set('Content-Type', 'text/plain');
    return res.status(200).send(content);
  } catch (err) {
    // with read errors print the error also to the console
    console.log(err.message);
    return res.status(500).send(err.message);
  }
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`Server running at port ${PORT}`);
});
