name: Release project (staging)

on:
  push:
    branches: ['main']
    paths:
      - 'broadcaster/**'
      - 'todo-app/**'
      - 'todo-backend/**'

env:
  REGISTRY: europe-north1-docker.pkg.dev
  REPOSITORY: docker-images

jobs:
  build-publish:
    name: Build and Publish
    runs-on: ubuntu-latest

    # Use environment scoped variables and secrets
    environment: GKE_PROJECT
    env:
      PROJECT_ID: '${{ vars.GKE_PROJECT_ID }}'

    # These are apparently required for Google Cloud Auth and Setup
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.SERVICE_ACCOUNT }}'

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v3

      - name: 'Configure Docker authentication with gcloud CLI'
        run: gcloud auth configure-docker "$REGISTRY"

      - name: Form the image names and save to environment
        id: image
        run: |-
          BROADCASTER_TAG="$REGISTRY/$PROJECT_ID/$REPOSITORY/broadcaster:main-$GITHUB_SHA"
          APP_TAG="$REGISTRY/$PROJECT_ID/$REPOSITORY/todo-app:main-$GITHUB_SHA"
          BACKEND_TAG="$REGISTRY/$PROJECT_ID/$REPOSITORY/todo-backend:main-$GITHUB_SHA"
          echo "BROADCASTER_TAG=$BROADCASTER_TAG" >> "$GITHUB_ENV"
          echo "APP_TAG=$APP_TAG" >> "$GITHUB_ENV"
          echo "BACKEND_TAG=$BACKEND_TAG" >> "$GITHUB_ENV"

      - name: Build broadcaster
        working-directory: broadcaster
        run: docker build --tag "$BROADCASTER_TAG" .

      - name: Build todo-app
        working-directory: todo-app
        run: docker build --tag "$APP_TAG" .

      - name: Build todo-backend
        working-directory: todo-backend
        run: docker build --tag "$BACKEND_TAG" .

      - name: Publish all
        run: |-
          docker push "$BROADCASTER_TAG"
          docker push "$APP_TAG"
          docker push "$BACKEND_TAG"
